version: "{build}-{branch}"
image: Visual Studio 2019
build: off
deploy: off
clone_folder: C:\projects\scoop
environment:
  scoop: C:\projects\scoop
  scoop_home: C:\projects\scoop
  scoop_helpers: C:\projects\helpers
  lessmsi: '%scoop_helpers%\lessmsi\lessmsi.exe'
  innounp: '%scoop_helpers%\innounp\innounp.exe'
  matrix:
    - PowerShell: 5
    - PowerShell: 7
cache:
  - '%USERPROFILE%\Documents\WindowsPowerShell\Modules -> appveyor.yml, test\bin\*.ps1'
  - C:\projects\helpers  -> appveyor.yml, test\bin\*.ps1
matrix:
  fast_finish: true
for:
  - matrix:
      only:
        - PowerShell: 5
    install:
      - ps: . "$env:SCOOP_HOME\test\bin\init.ps1"
    test_script:
      - ps: . "$env:SCOOP_HOME\test\bin\test.ps1"
  - matrix:
      only:
        - PowerShell: 7
    install:
      - pwsh: . "$env:SCOOP_HOME\test\bin\init.ps1"
    test_script:
      - pwsh: . "$env:SCOOP_HOME\test\bin\test.ps1"
